### ISSUE TITLE
Something is broken

### ISSUE THREAD

**Issue by tvdk-sudoku** [NotTacoz/startpage#4]
Something is broken, find the problem:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/85726678/167542358-42d48b1d-94da-43b5-9de3-e642aaaf367a.png">

**Comment by tms-h** [comment]
What seems to be the problem? Looks fine to me. 

Is it because you are on a windows computer when you usually are on a mac?

If this is about the empty square on the top right, that is a note (empty tab) that you can write on. You can simply click on it and type away, or you can toggle it off in settings!

**Comment by tvdk-sudoku** [comment]
No. It is the 12:24 AM part. AM!

**Comment by tms-h** [comment]
my bad

**Comment by tms-h** [comment]
fixed.
